s = set()
num = int(input("Enter the number of elements: "))
s.add(num)
num = int(input("Enter the number of elements: "))
s.add(num)
num = int(input("Enter the number of elements: "))
s.add(num)
num = int(input("Enter the number of elements: "))
s.add(num)
num = int(input("Enter the number of elements: "))
s.add(num)
num = int(input("Enter the number of elements: "))
s.add(num)
num = int(input("Enter the number of elements: "))
s.add(num)
num = int(input("Enter the number of elements: "))
s.add(num)

print(f"The set is: {s}")